import type { Analysis, GraveyardSettings, Repo } from "./types";
import { analyzeRepo, enrichAnalysisWithEvidence, toSignals } from "./analysis";

function a(partial: Analysis): Analysis {
  return partial;
}

export const DEFAULT_SETTINGS: GraveyardSettings = {
  humorEnabled: true,
  githubUsername: null,
  lastImportedAt: null,
};

const analyzedAt = "2026-08-18T16:00:00.000Z";

export const DEMO_REPOS: Repo[] = [
  {
    id: "demo-agent-dashboard",
    name: "agent-dashboard",
    fullName: "demo/agent-dashboard",
    description: "Local-first control plane for routing, reviewing, and dispatching specialized AI agents.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 78, CSS: 12, Python: 10 },
    stars: 4,
    forks: 0,
    openIssues: 11,
    openPrs: 1,
    lastCommitAt: "2026-05-12T21:14:00.000Z",
    createdAtGh: "2026-01-08T18:00:00.000Z",
    pushedAt: "2026-05-12T21:14:00.000Z",
    sizeKb: 18420,
    defaultBranch: "main",
    branchCount: 6,
    commitCount: 214,
    readmeQuality: 72,
    hasTests: true,
    hasCi: true,
    hasDeploy: false,
    hasAuth: true,
    hasDb: true,
    todoCount: 27,
    frameworks: ["React", "TanStack", "Fastify", "SQLite"],
    topics: ["agents", "orchestration", "dashboard"],
    htmlUrl: "https://github.com/demo/agent-dashboard",
    fileTree: [
      "src/app/layout.tsx",
      "src/features/dispatch/DispatchBoard.tsx",
      "src/features/agents/AgentCard.tsx",
      "src/server/router.ts",
      "src/server/memory.ts",
      "packages/protocol/index.ts",
      "README.md",
      "docker-compose.yml",
    ],
    packageManifests: ["package.json", "pnpm-workspace.yaml"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A control plane for running multiple local AI agents: assign work, inspect traces, and keep a persistent memory of what each agent has done.",
      currentState: "mvp",
      whatsMissing: ["Deployment", "UI/UX", "Testing", "Documentation"],
      recommendation: "FINISH",
      recommendationReason:
        "This is the most complete expression of a problem you keep re-solving. The dispatch loop already works. Shipping a durable local install would retire two overlapping experiments and give you a daily driver.",
      workRemaining: "medium",
      workTasks: [
        "Stabilize the agent protocol types and drop the duplicate dashboard-v2 models",
        "Replace the half-rewritten settings UI",
        "Add a one-command local install + backup",
        "Cover the dispatch/review loop with integration tests",
      ],
      completionPct: 62,
      complexity: 4,
      maintenanceBurden: 68,
      usefulness: 88,
      commercialPotential: 54,
      ossPotential: 61,
      personalUsefulness: 91,
      portfolioValue: 78,
      ossValue: 64,
      learningValue: 70,
      resurrectionScore: 86,
      epitaph: "Technically only needed one more weekend.",
      causeOfDeath: "Started rewriting the frontend.",
      bornDate: "2026-01-08",
      overlaps: [
        {
          repoId: "demo-ops-console",
          name: "ops-console",
          percent: 74,
          note: "Same control-plane idea with a newer sidebar and almost no backend. Fold the UI experiments into this repo.",
        },
        {
          repoId: "demo-whisper-bot",
          name: "whisper-bot",
          percent: 48,
          note: "Chat surface overlaps with the agent inbox. Keep the prompt tooling; drop the second shell.",
        },
      ],
      facts: [
        "214 commits, last push 12 May 2026",
        "Has auth, SQLite, and a working dispatch board",
        "11 open issues, 27 TODO/FIXME comments",
        "CI runs unit tests; no deploy config",
      ],
      assumptions: [
        "The rewrite branch is abandoned, not secretly better",
        "You still want a local-first agent runner rather than a hosted one",
      ],
      mvpDefinition:
        "A signed-in user can register an agent, dispatch a job, read the trace, and resume after a restart without losing memory.",
      milestones: [
        { id: "m1", title: "Freeze protocol types", done: true },
        { id: "m2", title: "Ship the current UI without a rewrite", done: false },
        { id: "m3", title: "Local install + backup", done: false },
        { id: "m4", title: "Dispatch loop tests", done: false },
      ],
      taskList: [
        { id: "t1", title: "Delete the rewrite branch and restore the working settings page", estimate: "small" },
        { id: "t2", title: "Add SQLite backup/restore in the setup command", estimate: "small" },
        { id: "t3", title: "Write 8 integration tests around dispatch → review → memory", estimate: "medium" },
        { id: "t4", title: "Write a 2-page operator README", estimate: "tiny" },
      ],
      firstTask: "Delete the rewrite branch and restore the working settings page",
      dependencies: ["ops-console UI pieces", "whisper-bot prompt templates"],
      blockers: ["Unfinished frontend rewrite sitting on main-adjacent branch"],
      definitionOfDone:
        "Fresh clone, one command, you can dispatch a job and see it after reboot. README describes the happy path.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-ops-console",
    name: "ops-console",
    fullName: "demo/ops-console",
    description: "Second attempt at an agent operations console with a denser layout.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 86, CSS: 14 },
    stars: 0,
    forks: 0,
    openIssues: 3,
    openPrs: 0,
    lastCommitAt: "2026-06-02T11:40:00.000Z",
    createdAtGh: "2026-04-19T16:20:00.000Z",
    pushedAt: "2026-06-02T11:40:00.000Z",
    sizeKb: 6200,
    defaultBranch: "main",
    branchCount: 3,
    commitCount: 41,
    readmeQuality: 28,
    hasTests: false,
    hasCi: false,
    hasDeploy: false,
    hasAuth: false,
    hasDb: false,
    todoCount: 14,
    frameworks: ["React", "Vite", "Tailwind"],
    topics: ["dashboard", "agents"],
    htmlUrl: "https://github.com/demo/ops-console",
    fileTree: ["src/App.tsx", "src/Sidebar.tsx", "src/mockAgents.ts", "README.md"],
    packageManifests: ["package.json"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A visual redesign of the agent dashboard: denser tables, a new sidebar, mock data. No backend of its own.",
      currentState: "early",
      whatsMissing: ["Core functionality", "Authentication", "Database work", "Testing"],
      recommendation: "MERGE",
      recommendationReason:
        "This is a UI sketch of agent-dashboard, not a separate product. The sidebar and table density are the only parts worth keeping. Maintaining both will guarantee neither ships.",
      workRemaining: "small",
      workTasks: [
        "Extract the sidebar and data-table density into a patch for agent-dashboard",
        "Archive this repository after the merge",
      ],
      completionPct: 22,
      complexity: 2,
      maintenanceBurden: 35,
      usefulness: 40,
      commercialPotential: 18,
      ossPotential: 12,
      personalUsefulness: 34,
      portfolioValue: 25,
      ossValue: 10,
      learningValue: 42,
      resurrectionScore: 31,
      epitaph: "Replaced by a newer project doing almost exactly the same thing.",
      causeOfDeath: "Spawned as a rewrite of agent-dashboard.",
      bornDate: "2026-04-19",
      overlaps: [
        {
          repoId: "demo-agent-dashboard",
          name: "agent-dashboard",
          percent: 74,
          note: "Purpose, stack, and information architecture are the same. Merge UI, then archive.",
        },
      ],
      facts: [
        "41 commits, mock data only",
        "No auth, database, tests, or CI",
        "README is a title and three bullet points",
      ],
      assumptions: ["The visual ideas are still desirable in agent-dashboard"],
      mvpDefinition: "Not a standalone MVP — a UI patch for agent-dashboard.",
      milestones: [
        { id: "m1", title: "Port sidebar", done: false },
        { id: "m2", title: "Archive repo", done: false },
      ],
      taskList: [
        { id: "t1", title: "Copy Sidebar.tsx patterns into agent-dashboard", estimate: "small" },
        { id: "t2", title: "Archive ops-console", estimate: "tiny" },
      ],
      firstTask: "Copy Sidebar.tsx patterns into agent-dashboard",
      dependencies: ["agent-dashboard"],
      blockers: ["Diverging component APIs"],
      definitionOfDone: "Useful UI is in agent-dashboard; this repo is archived.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-whisper-bot",
    name: "whisper-bot",
    fullName: "demo/whisper-bot",
    description: "Experimental chatbot with tool calling, memory notes, and a scratch UI.",
    isPrivate: true,
    isFork: false,
    language: "Python",
    languages: { Python: 81, TypeScript: 19 },
    stars: 2,
    forks: 0,
    openIssues: 6,
    openPrs: 0,
    lastCommitAt: "2026-03-29T09:12:00.000Z",
    createdAtGh: "2025-11-02T20:00:00.000Z",
    pushedAt: "2026-03-29T09:12:00.000Z",
    sizeKb: 4100,
    defaultBranch: "main",
    branchCount: 4,
    commitCount: 96,
    readmeQuality: 44,
    hasTests: false,
    hasCi: false,
    hasDeploy: false,
    hasAuth: false,
    hasDb: true,
    todoCount: 19,
    frameworks: ["FastAPI", "React", "SQLite"],
    topics: ["chatbot", "llm", "tools"],
    htmlUrl: "https://github.com/demo/whisper-bot",
    fileTree: ["app/main.py", "app/tools.py", "app/memory.py", "web/Chat.tsx", "README.md"],
    packageManifests: ["pyproject.toml", "web/package.json"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A playground chatbot used to test tool-calling patterns, memory notes, and prompt templates against local models.",
      currentState: "early",
      whatsMissing: ["UI/UX", "Testing", "Authentication", "Refactoring"],
      recommendation: "MERGE",
      recommendationReason:
        "The value is the tool-calling notes and prompt templates, not the chat shell. Those belong in agent-dashboard and prompt-library. The UI is a dead end.",
      workRemaining: "small",
      workTasks: [
        "Lift tool schemas into the agent protocol package",
        "Move durable prompts into prompt-library",
        "Archive the chat UI",
      ],
      completionPct: 34,
      complexity: 3,
      maintenanceBurden: 48,
      usefulness: 51,
      commercialPotential: 22,
      ossPotential: 30,
      personalUsefulness: 47,
      portfolioValue: 33,
      ossValue: 28,
      learningValue: 66,
      resurrectionScore: 38,
      epitaph: "Killed by a better inbox in another repo.",
      causeOfDeath: "Became a prompt scratchpad with a chat window glued on.",
      bornDate: "2025-11-02",
      overlaps: [
        {
          repoId: "demo-agent-dashboard",
          name: "agent-dashboard",
          percent: 48,
          note: "Agent inbox already covers conversation + tools.",
        },
        {
          repoId: "demo-prompt-library",
          name: "prompt-library",
          percent: 41,
          note: "Durable prompts should live in the library, not in this bot.",
        },
      ],
      facts: [
        "Last commit 29 Mar 2026",
        "SQLite memory table exists; no tests",
        "Web UI is a single Chat.tsx file",
      ],
      assumptions: ["Tool schemas are still accurate"],
      mvpDefinition: "Extracted tools + prompts, chat UI retired.",
      milestones: [
        { id: "m1", title: "Export tool schemas", done: false },
        { id: "m2", title: "Move prompts", done: false },
      ],
      taskList: [
        { id: "t1", title: "Copy app/tools.py schemas into agent-dashboard protocol", estimate: "small" },
        { id: "t2", title: "Add the five durable prompts to prompt-library", estimate: "tiny" },
      ],
      firstTask: "Copy app/tools.py schemas into agent-dashboard protocol",
      dependencies: ["agent-dashboard", "prompt-library"],
      blockers: [],
      definitionOfDone: "No unique logic remains here; repository archived.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-prompt-library",
    name: "prompt-library",
    fullName: "demo/prompt-library",
    description: "Versioned JSON prompt collection with tags, evaluations, and a tiny reviewer UI.",
    isPrivate: false,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 54, JSON: 38, CSS: 8 },
    stars: 18,
    forks: 3,
    openIssues: 4,
    openPrs: 1,
    lastCommitAt: "2026-08-06T19:22:00.000Z",
    createdAtGh: "2025-09-14T14:00:00.000Z",
    pushedAt: "2026-08-06T19:22:00.000Z",
    sizeKb: 2300,
    defaultBranch: "main",
    branchCount: 2,
    commitCount: 167,
    readmeQuality: 88,
    hasTests: true,
    hasCi: true,
    hasDeploy: true,
    hasAuth: false,
    hasDb: false,
    todoCount: 3,
    frameworks: ["Vite", "Zod"],
    topics: ["prompts", "llm", "json"],
    homepage: "https://prompts.example.dev",
    htmlUrl: "https://github.com/demo/prompt-library",
    fileTree: ["prompts/", "src/reviewer.tsx", "schema/prompt.ts", "README.md", ".github/workflows/ci.yml"],
    packageManifests: ["package.json"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A public, versioned library of structured prompts with a schema, tags, and a small reviewer so you can diff what actually works.",
      currentState: "mostly_complete",
      whatsMissing: ["Documentation", "Integrations"],
      recommendation: "OPEN_SOURCE",
      recommendationReason:
        "It is already public, documented, and useful to other people. The remaining work is packaging and a contribution guide — not more product. Treat it as a library, not a startup.",
      workRemaining: "small",
      workTasks: [
        "Add CONTRIBUTING.md and a versioning policy",
        "Publish the schema as an npm package",
        "Add five example evaluations to the README",
      ],
      completionPct: 84,
      complexity: 2,
      maintenanceBurden: 32,
      usefulness: 76,
      commercialPotential: 24,
      ossPotential: 91,
      personalUsefulness: 70,
      portfolioValue: 82,
      ossValue: 90,
      learningValue: 45,
      resurrectionScore: 79,
      epitaph: "Still alive — just never formally released.",
      causeOfDeath: "Never written up as a real open-source project.",
      bornDate: "2025-09-14",
      overlaps: [
        {
          repoId: "demo-whisper-bot",
          name: "whisper-bot",
          percent: 41,
          note: "Bot contains stray prompts that belong here.",
        },
      ],
      facts: [
        "Public repo, 18 stars, CI green",
        "Last commit 6 Aug 2026 — this one is not dormant",
        "Zod schema and reviewer UI exist",
      ],
      assumptions: ["You are willing to accept outside contributions"],
      mvpDefinition:
        "npm package + contribution guide + tagged v1.0 so others can depend on the schema.",
      milestones: [
        { id: "m1", title: "Schema freeze", done: true },
        { id: "m2", title: "Publish package", done: false },
        { id: "m3", title: "v1.0 tag", done: false },
      ],
      taskList: [
        { id: "t1", title: "Write CONTRIBUTING.md and versioning rules", estimate: "tiny" },
        { id: "t2", title: "Publish @demo/prompt-schema to npm", estimate: "small" },
      ],
      firstTask: "Write CONTRIBUTING.md and versioning rules",
      dependencies: [],
      blockers: [],
      definitionOfDone: "Tagged v1.0, package published, issues template in place.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-parcel-atlas",
    name: "parcel-atlas",
    fullName: "demo/parcel-atlas",
    description: "County parcel explorer with PostGIS, ownership traces, and saved map views.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 71, SQL: 18, Python: 11 },
    stars: 1,
    forks: 0,
    openIssues: 9,
    openPrs: 0,
    lastCommitAt: "2026-07-09T22:05:00.000Z",
    createdAtGh: "2026-02-11T13:30:00.000Z",
    pushedAt: "2026-07-09T22:05:00.000Z",
    sizeKb: 22100,
    defaultBranch: "main",
    branchCount: 5,
    commitCount: 188,
    readmeQuality: 61,
    hasTests: true,
    hasCi: false,
    hasDeploy: false,
    hasAuth: true,
    hasDb: true,
    todoCount: 16,
    frameworks: ["React", "MapLibre", "PostgreSQL", "PostGIS"],
    topics: ["gis", "real-estate", "maps"],
    htmlUrl: "https://github.com/demo/parcel-atlas",
    fileTree: [
      "src/map/MapView.tsx",
      "src/search/ParcelSearch.tsx",
      "server/tiles.ts",
      "sql/schema.sql",
      "README.md",
    ],
    packageManifests: ["package.json"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A map-first explorer for county parcel and ownership data: search a lot, see history, save views. Built on PostGIS.",
      currentState: "mvp",
      whatsMissing: ["Deployment", "Performance", "Documentation", "Security"],
      recommendation: "PRODUCTIZE",
      recommendationReason:
        "This solves a real, paid-for workflow and already has the hard part (spatial data + search). The gap is packaging: hosted tiles, a billing wall, and a county-onboarding script — not more map features.",
      workRemaining: "large",
      workTasks: [
        "Host vector tiles and add a county import job",
        "Add a simple seat-based billing page",
        "Lock down the API (rate limit, API keys)",
        "Write an onboarding runbook for a second county",
      ],
      completionPct: 58,
      complexity: 4,
      maintenanceBurden: 72,
      usefulness: 80,
      commercialPotential: 84,
      ossPotential: 36,
      personalUsefulness: 62,
      portfolioValue: 81,
      ossValue: 34,
      learningValue: 74,
      resurrectionScore: 83,
      epitaph: "Killed by 'I'll productize it later.'",
      causeOfDeath: "Got useful locally, never deployed.",
      bornDate: "2026-02-11",
      overlaps: [],
      facts: [
        "PostGIS schema and MapLibre view work on a local dump",
        "Auth exists; no production deploy",
        "Last meaningful commit 9 Jul 2026",
      ],
      assumptions: [
        "There is a county or brokerage that would pay for hosted access",
        "Data licensing allows a commercial wrapper",
      ],
      mvpDefinition:
        "One county loaded in production, a user can search a parcel, save a view, and invite a teammate.",
      milestones: [
        { id: "m1", title: "Local map + search", done: true },
        { id: "m2", title: "Production tiles", done: false },
        { id: "m3", title: "Team invite + billing", done: false },
      ],
      taskList: [
        { id: "t1", title: "Stand up hosted PostGIS + tile server", estimate: "medium" },
        { id: "t2", title: "County import CLI with a dry-run", estimate: "medium" },
        { id: "t3", title: "API keys and basic rate limits", estimate: "small" },
        { id: "t4", title: "Seat billing via a hosted checkout", estimate: "medium" },
      ],
      firstTask: "Stand up hosted PostGIS + tile server",
      dependencies: ["A production Postgres with PostGIS"],
      blockers: ["Unclear data-licensing for redistribution"],
      definitionOfDone:
        "A second person can log in, search a parcel in the seeded county, and not need your laptop.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-ledgerline",
    name: "ledgerline",
    fullName: "demo/ledgerline",
    description: "Nearly finished SaaS for service-department workload and advisor performance.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 82, SQL: 10, CSS: 8 },
    stars: 0,
    forks: 0,
    openIssues: 7,
    openPrs: 2,
    lastCommitAt: "2026-07-31T18:48:00.000Z",
    createdAtGh: "2026-03-03T10:00:00.000Z",
    pushedAt: "2026-07-31T18:48:00.000Z",
    sizeKb: 15600,
    defaultBranch: "main",
    branchCount: 4,
    commitCount: 251,
    readmeQuality: 70,
    hasTests: true,
    hasCi: true,
    hasDeploy: true,
    hasAuth: true,
    hasDb: true,
    todoCount: 8,
    frameworks: ["Next.js", "Postgres", "Stripe", "Tailwind"],
    topics: ["saas", "operations", "reports"],
    htmlUrl: "https://github.com/demo/ledgerline",
    fileTree: [
      "app/dashboard/page.tsx",
      "app/advisors/page.tsx",
      "lib/reports.ts",
      "lib/billing.ts",
      "README.md",
      "vercel.json",
    ],
    packageManifests: ["package.json"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A small SaaS that turns service-advisor performance exports into a weekly operating review: close rate, comebacks, hours, coaching notes.",
      currentState: "mostly_complete",
      whatsMissing: ["Documentation", "Integrations", "Performance"],
      recommendation: "PRODUCTIZE",
      recommendationReason:
        "Auth, billing, and the core report already exist. This is closer to a first customer than to a prototype. Remaining work is onboarding polish and a CSV importer other stores can use without you.",
      workRemaining: "medium",
      workTasks: [
        "Generic CSV importer with column mapping",
        "First-run checklist and sample dataset",
        "Usage-limited billing that matches the actual plan",
        "A one-page 'how a store uses this on Monday'",
      ],
      completionPct: 81,
      complexity: 3,
      maintenanceBurden: 55,
      usefulness: 86,
      commercialPotential: 88,
      ossPotential: 20,
      personalUsefulness: 84,
      portfolioValue: 80,
      ossValue: 18,
      learningValue: 50,
      resurrectionScore: 91,
      epitaph: "Died on the one-yard line.",
      causeOfDeath: "Waiting for a perfect importer.",
      bornDate: "2026-03-03",
      overlaps: [],
      facts: [
        "Stripe billing and auth are wired",
        "Deploy config present; CI green",
        "Last commit 31 Jul 2026",
        "8 TODOs, mostly importer-related",
      ],
      assumptions: ["You still have access to a store that will trial it"],
      mvpDefinition:
        "A manager can upload last week's export, see the operating review, and invite one advisor.",
      milestones: [
        { id: "m1", title: "Core report", done: true },
        { id: "m2", title: "Billing", done: true },
        { id: "m3", title: "Generic importer", done: false },
        { id: "m4", title: "Onboarding", done: false },
      ],
      taskList: [
        { id: "t1", title: "CSV column mapper for the three common DMS exports", estimate: "medium" },
        { id: "t2", title: "First-run sample data + checklist", estimate: "small" },
        { id: "t3", title: "Monday one-pager in the empty state", estimate: "tiny" },
      ],
      firstTask: "CSV column mapper for the three common DMS exports",
      dependencies: ["A real export file to test against"],
      blockers: ["Column names differ by store"],
      definitionOfDone:
        "Someone who is not you can upload a CSV and get the weekly review without a Slack thread.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-forge-cli",
    name: "forge-cli",
    fullName: "demo/forge-cli",
    description: "Half-built CLI for scaffolding local agent workspaces and doctoring env files.",
    isPrivate: false,
    isFork: false,
    language: "Go",
    languages: { Go: 100 },
    stars: 6,
    forks: 1,
    openIssues: 5,
    openPrs: 0,
    lastCommitAt: "2026-04-18T15:09:00.000Z",
    createdAtGh: "2026-01-22T09:40:00.000Z",
    pushedAt: "2026-04-18T15:09:00.000Z",
    sizeKb: 890,
    defaultBranch: "main",
    branchCount: 2,
    commitCount: 54,
    readmeQuality: 55,
    hasTests: true,
    hasCi: true,
    hasDeploy: false,
    hasAuth: false,
    hasDb: false,
    todoCount: 7,
    frameworks: ["Cobra", "Go"],
    topics: ["cli", "devtools"],
    htmlUrl: "https://github.com/demo/forge-cli",
    fileTree: ["cmd/forge/main.go", "internal/doctor/doctor.go", "internal/scaffold/scaffold.go", "README.md"],
    packageManifests: ["go.mod"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A small CLI that scaffolds an agent workspace and checks that the local env (models, keys, directories) is sane.",
      currentState: "early",
      whatsMissing: ["Core functionality", "Documentation", "Testing"],
      recommendation: "FINISH",
      recommendationReason:
        "Scope is tiny and the doctor command already works. Finishing `forge init` would pay rent every time you start a new agent experiment. Easy win.",
      workRemaining: "small",
      workTasks: [
        "Finish `forge init` templates",
        "Add `--json` output for the doctor command",
        "Write four golden-file tests",
        "Tag v0.1 and add brew/go install notes",
      ],
      completionPct: 46,
      complexity: 2,
      maintenanceBurden: 22,
      usefulness: 71,
      commercialPotential: 12,
      ossPotential: 58,
      personalUsefulness: 77,
      portfolioValue: 54,
      ossValue: 57,
      learningValue: 40,
      resurrectionScore: 72,
      epitaph: "Killed by a yak-shave in the template engine.",
      causeOfDeath: "Stopped while rewriting flag parsing.",
      bornDate: "2026-01-22",
      overlaps: [],
      facts: [
        "Doctor command has tests; init is stubbed",
        "Public, 6 stars",
        "Last commit 18 Apr 2026",
      ],
      assumptions: ["You still start new agent repos often enough to care"],
      mvpDefinition: "`forge init` creates a workspace; `forge doctor` exits non-zero on a broken env.",
      milestones: [
        { id: "m1", title: "Doctor command", done: true },
        { id: "m2", title: "Init templates", done: false },
      ],
      taskList: [
        { id: "t1", title: "Write the default workspace template", estimate: "small" },
        { id: "t2", title: "Golden-file tests for init", estimate: "tiny" },
        { id: "t3", title: "README install section", estimate: "tiny" },
      ],
      firstTask: "Write the default workspace template",
      dependencies: [],
      blockers: [],
      definitionOfDone: "A stranger can `go install` and scaffold a workspace in one minute.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-runbook",
    name: "runbook",
    fullName: "demo/runbook",
    description: "Automation framework for scheduled jobs, retries, and human-in-the-loop approvals.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 93, JSON: 7 },
    stars: 0,
    forks: 0,
    openIssues: 8,
    openPrs: 0,
    lastCommitAt: "2026-06-28T20:11:00.000Z",
    createdAtGh: "2026-02-02T11:15:00.000Z",
    pushedAt: "2026-06-28T20:11:00.000Z",
    sizeKb: 7400,
    defaultBranch: "main",
    branchCount: 3,
    commitCount: 129,
    readmeQuality: 50,
    hasTests: true,
    hasCi: true,
    hasDeploy: false,
    hasAuth: false,
    hasDb: true,
    todoCount: 11,
    frameworks: ["Node", "SQLite", "Zod"],
    topics: ["automation", "jobs", "cron"],
    htmlUrl: "https://github.com/demo/runbook",
    fileTree: ["src/scheduler.ts", "src/jobs/", "src/approvals.ts", "README.md"],
    packageManifests: ["package.json"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A local automation runner: define jobs, retry them, and pause for a human approval before a side effect.",
      currentState: "mvp",
      whatsMissing: ["UI/UX", "Deployment", "Documentation"],
      recommendation: "FINISH",
      recommendationReason:
        "The scheduler and approval primitive are real. A thin TUI or web list would make this something you actually run, instead of a library you forget. Scope is contained.",
      workRemaining: "medium",
      workTasks: [
        "Ship a minimal job list UI (or TUI)",
        "Persist approval tokens across restarts",
        "Document how to add a job in 20 lines",
        "Add a systemd/launchd example",
      ],
      completionPct: 57,
      complexity: 3,
      maintenanceBurden: 46,
      usefulness: 74,
      commercialPotential: 28,
      ossPotential: 49,
      personalUsefulness: 80,
      portfolioValue: 60,
      ossValue: 47,
      learningValue: 58,
      resurrectionScore: 69,
      epitaph: "Paused for approval. Forever.",
      causeOfDeath: "No UI, so it never entered daily use.",
      bornDate: "2026-02-02",
      overlaps: [],
      facts: [
        "SQLite job log exists",
        "CI on tests",
        "Last commit 28 Jun 2026",
      ],
      assumptions: ["You have at least three jobs you would actually schedule"],
      mvpDefinition: "Three real jobs running locally with one approval step that survives restart.",
      milestones: [
        { id: "m1", title: "Scheduler + retries", done: true },
        { id: "m2", title: "Approvals persist", done: false },
        { id: "m3", title: "Job list UI", done: false },
      ],
      taskList: [
        { id: "t1", title: "Persist approvals to SQLite", estimate: "small" },
        { id: "t2", title: "Minimal job list page", estimate: "medium" },
        { id: "t3", title: "README with a 20-line job", estimate: "tiny" },
      ],
      firstTask: "Persist approvals to SQLite",
      dependencies: [],
      blockers: [],
      definitionOfDone: "A job can wait for you, survive reboot, and then run.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-deal-hunter",
    name: "deal-hunter",
    fullName: "demo/deal-hunter",
    description: "Multi-agent pipeline that reviews listings and drafts a short buy/pass memo.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 64, Python: 36 },
    stars: 0,
    forks: 0,
    openIssues: 12,
    openPrs: 0,
    lastCommitAt: "2026-07-11T17:33:00.000Z",
    createdAtGh: "2026-05-01T12:00:00.000Z",
    pushedAt: "2026-07-11T17:33:00.000Z",
    sizeKb: 9800,
    defaultBranch: "main",
    branchCount: 7,
    commitCount: 102,
    readmeQuality: 40,
    hasTests: false,
    hasCi: false,
    hasDeploy: false,
    hasAuth: false,
    hasDb: true,
    todoCount: 23,
    frameworks: ["LangGraph", "FastAPI", "Playwright"],
    topics: ["agents", "scraping", "research"],
    htmlUrl: "https://github.com/demo/deal-hunter",
    fileTree: ["graph/pipeline.py", "src/memo.tsx", "scrapers/", "README.md"],
    packageManifests: ["package.json", "pyproject.toml"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A research pipeline: scrape listings, run specialist agents, emit a buy/pass memo a human can actually read.",
      currentState: "early",
      whatsMissing: ["Core functionality", "Testing", "Reliability", "Documentation"],
      recommendation: "FINISH",
      recommendationReason:
        "The memo format is the asset. The scrapers are the liability. Narrow to one listing source, make the memo deterministic, and stop pretending this is a platform.",
      workRemaining: "large",
      workTasks: [
        "Pick one listing source and delete the others",
        "Freeze the memo schema",
        "Add replay tests from saved HTML",
        "Queue failed scrapes instead of crashing the graph",
      ],
      completionPct: 37,
      complexity: 5,
      maintenanceBurden: 81,
      usefulness: 66,
      commercialPotential: 47,
      ossPotential: 22,
      personalUsefulness: 73,
      portfolioValue: 58,
      ossValue: 20,
      learningValue: 82,
      resurrectionScore: 61,
      epitaph: "Killed by a third scraper.",
      causeOfDeath: "Scope expanded every time a listing site changed markup.",
      bornDate: "2026-05-01",
      overlaps: [
        {
          repoId: "demo-agent-dashboard",
          name: "agent-dashboard",
          percent: 33,
          note: "Could run as a job inside the dashboard instead of a standalone graph.",
        },
      ],
      facts: [
        "7 branches, 23 TODOs",
        "No CI, no tests",
        "Last commit 11 Jul 2026",
      ],
      assumptions: ["There is still a listings workflow you personally run"],
      mvpDefinition: "One source in, one memo out, replayable from a fixture.",
      milestones: [
        { id: "m1", title: "Memo schema", done: true },
        { id: "m2", title: "Single scraper", done: false },
        { id: "m3", title: "Replay tests", done: false },
      ],
      taskList: [
        { id: "t1", title: "Delete all scrapers except the primary source", estimate: "small" },
        { id: "t2", title: "Save 10 listing fixtures and assert memo fields", estimate: "medium" },
        { id: "t3", title: "Dead-letter queue for failed fetches", estimate: "small" },
      ],
      firstTask: "Delete all scrapers except the primary source",
      dependencies: ["agent-dashboard optional later"],
      blockers: ["Listing markup changes"],
      definitionOfDone: "Given a saved listing, the memo is stable and reviewable.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-local-model-bench",
    name: "local-model-bench",
    fullName: "demo/local-model-bench",
    description: "Benchmark harness for local LLMs: latency, tokens, and a handful of eval prompts.",
    isPrivate: false,
    isFork: false,
    language: "Python",
    languages: { Python: 100 },
    stars: 11,
    forks: 2,
    openIssues: 2,
    openPrs: 0,
    lastCommitAt: "2025-12-19T08:44:00.000Z",
    createdAtGh: "2025-06-07T16:10:00.000Z",
    pushedAt: "2025-12-19T08:44:00.000Z",
    sizeKb: 1600,
    defaultBranch: "main",
    branchCount: 1,
    commitCount: 73,
    readmeQuality: 64,
    hasTests: true,
    hasCi: false,
    hasDeploy: false,
    hasAuth: false,
    hasDb: false,
    todoCount: 4,
    frameworks: ["pytest", "Ollama"],
    topics: ["llm", "benchmarks"],
    htmlUrl: "https://github.com/demo/local-model-bench",
    fileTree: ["bench/run.py", "bench/prompts.yaml", "README.md"],
    packageManifests: ["pyproject.toml"],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose:
        "A script that times local models on a fixed prompt set and prints a table of latency and tokens.",
      currentState: "legacy",
      whatsMissing: ["Core functionality", "Documentation"],
      recommendation: "ARCHIVE",
      recommendationReason:
        "Useful in 2025, now superseded by better harnesses and by notes already in prompt-library. Keeping it unarchived implies you will update the model list. You will not.",
      workRemaining: "small",
      workTasks: ["Snapshot the last results into prompt-library", "Archive the repository"],
      completionPct: 70,
      complexity: 2,
      maintenanceBurden: 40,
      usefulness: 28,
      commercialPotential: 5,
      ossPotential: 25,
      personalUsefulness: 22,
      portfolioValue: 30,
      ossValue: 24,
      learningValue: 18,
      resurrectionScore: 19,
      epitaph: "Outrun by the thing it was measuring.",
      causeOfDeath: "Model list went stale and was never refreshed.",
      bornDate: "2025-06-07",
      overlaps: [
        {
          repoId: "demo-prompt-library",
          name: "prompt-library",
          percent: 29,
          note: "Eval prompts overlap; keep the prompts, drop the harness.",
        },
      ],
      facts: [
        "Last commit Dec 2025",
        "Single branch, public",
        "Tests exist for the table formatter",
      ],
      assumptions: ["You are not about to start a local-model bake-off"],
      mvpDefinition: "N/A — archive.",
      milestones: [{ id: "m1", title: "Archive", done: false }],
      taskList: [
        { id: "t1", title: "Copy remaining eval prompts into prompt-library", estimate: "tiny" },
        { id: "t2", title: "Archive on GitHub", estimate: "tiny" },
      ],
      firstTask: "Copy remaining eval prompts into prompt-library",
      dependencies: ["prompt-library"],
      blockers: [],
      definitionOfDone: "Repo archived; unique prompts preserved.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-v1-portfolio",
    name: "v1-portfolio",
    fullName: "demo/v1-portfolio",
    description: "First personal site. Hand-rolled HTML, a project grid, and a now-broken contact form.",
    isPrivate: false,
    isFork: false,
    language: "HTML",
    languages: { HTML: 62, CSS: 30, JavaScript: 8 },
    stars: 0,
    forks: 0,
    openIssues: 0,
    openPrs: 0,
    lastCommitAt: "2024-04-02T19:00:00.000Z",
    createdAtGh: "2023-08-20T12:00:00.000Z",
    pushedAt: "2024-04-02T19:00:00.000Z",
    sizeKb: 420,
    defaultBranch: "main",
    branchCount: 1,
    commitCount: 38,
    readmeQuality: 20,
    hasTests: false,
    hasCi: false,
    hasDeploy: true,
    hasAuth: false,
    hasDb: false,
    todoCount: 1,
    frameworks: ["HTML"],
    topics: ["portfolio"],
    htmlUrl: "https://github.com/demo/v1-portfolio",
    fileTree: ["index.html", "styles.css", "projects.html", "CNAME"],
    packageManifests: [],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose: "A static personal portfolio from 2023, with a project grid and an email form that posts nowhere.",
      currentState: "legacy",
      whatsMissing: ["Core functionality"],
      recommendation: "ARCHIVE",
      recommendationReason:
        "Superseded as a public face and not interesting as a code sample. Keep the writing if any; archive the rest. No resurrection case.",
      workRemaining: "tiny",
      workTasks: ["Save any unique copy", "Archive"],
      completionPct: 90,
      complexity: 1,
      maintenanceBurden: 10,
      usefulness: 8,
      commercialPotential: 0,
      ossPotential: 0,
      personalUsefulness: 6,
      portfolioValue: 12,
      ossValue: 0,
      learningValue: 5,
      resurrectionScore: 8,
      epitaph: "Here lies another personal site.",
      causeOfDeath: "Replaced by a later portfolio and never taken down.",
      bornDate: "2023-08-20",
      overlaps: [],
      facts: ["Last commit Apr 2024", "Public, zero stars", "Contact form has no endpoint"],
      assumptions: ["Nothing unique remains unpublished elsewhere"],
      mvpDefinition: "N/A — archive.",
      milestones: [{ id: "m1", title: "Archive", done: false }],
      taskList: [{ id: "t1", title: "Archive the GitHub repo", estimate: "tiny" }],
      firstTask: "Archive the GitHub repo",
      dependencies: [],
      blockers: [],
      definitionOfDone: "Repo archived.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-lantern-pixel",
    name: "lantern-pixel",
    fullName: "demo/lantern-pixel",
    description: "Tiny abandoned exploration game. One dungeon, broken collision, no save.",
    isPrivate: true,
    isFork: false,
    language: "JavaScript",
    languages: { JavaScript: 88, HTML: 12 },
    stars: 0,
    forks: 0,
    openIssues: 0,
    openPrs: 0,
    lastCommitAt: "2025-06-14T23:41:00.000Z",
    createdAtGh: "2025-04-11T21:00:00.000Z",
    pushedAt: "2025-06-14T23:41:00.000Z",
    sizeKb: 3100,
    defaultBranch: "main",
    branchCount: 2,
    commitCount: 47,
    readmeQuality: 15,
    hasTests: false,
    hasCi: false,
    hasDeploy: false,
    hasAuth: false,
    hasDb: false,
    todoCount: 9,
    frameworks: ["Canvas"],
    topics: ["game"],
    htmlUrl: "https://github.com/demo/lantern-pixel",
    fileTree: ["index.html", "src/game.js", "src/map.js", "src/player.js"],
    packageManifests: [],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose: "A weekend pixel exploration game: walk a dungeon, light lanterns, avoid one enemy type.",
      currentState: "abandoned",
      whatsMissing: ["Core functionality", "UI/UX"],
      recommendation: "ARCHIVE",
      recommendationReason:
        "A learning sketch with broken collision and no design doc. Finishing it would mean starting over. Keep it only if you want the sprites; otherwise bury it.",
      workRemaining: "massive",
      workTasks: ["Rewrite collision", "Add a second room", "Save games", "Combat that feels fair"],
      completionPct: 18,
      complexity: 3,
      maintenanceBurden: 25,
      usefulness: 12,
      commercialPotential: 4,
      ossPotential: 8,
      personalUsefulness: 15,
      portfolioValue: 20,
      ossValue: 8,
      learningValue: 35,
      resurrectionScore: 14,
      epitaph: "Killed by collision detection.",
      causeOfDeath: "Player fell through the floor and enthusiasm followed.",
      bornDate: "2025-04-11",
      overlaps: [],
      facts: ["47 commits over two months in 2025", "No README to speak of", "Private"],
      assumptions: ["You are not planning a game jam with this codebase"],
      mvpDefinition: "N/A — archive.",
      milestones: [{ id: "m1", title: "Archive", done: false }],
      taskList: [{ id: "t1", title: "Archive", estimate: "tiny" }],
      firstTask: "Archive",
      dependencies: [],
      blockers: ["Fundamentally unfinished engine"],
      definitionOfDone: "Repo archived.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-old-dotfiles",
    name: "old-dotfiles-experiment",
    fullName: "demo/old-dotfiles-experiment",
    description: "Throwaway shell experiment. Aliases that conflict with the real dotfiles repo.",
    isPrivate: true,
    isFork: false,
    language: "Shell",
    languages: { Shell: 100 },
    stars: 0,
    forks: 0,
    openIssues: 0,
    openPrs: 0,
    lastCommitAt: "2023-11-09T07:18:00.000Z",
    createdAtGh: "2023-10-02T07:00:00.000Z",
    pushedAt: "2023-11-09T07:18:00.000Z",
    sizeKb: 48,
    defaultBranch: "master",
    branchCount: 1,
    commitCount: 9,
    readmeQuality: 5,
    hasTests: false,
    hasCi: false,
    hasDeploy: false,
    hasAuth: false,
    hasDb: false,
    todoCount: 0,
    frameworks: ["bash"],
    topics: [],
    htmlUrl: "https://github.com/demo/old-dotfiles-experiment",
    fileTree: [".bashrc", "aliases.sh", "install.sh"],
    packageManifests: [],
    userStatus: "none",
    userNotes: "",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose: "A weekend attempt to reorganize shell aliases. Never became the real dotfiles repo.",
      currentState: "abandoned",
      whatsMissing: ["Core functionality", "Documentation"],
      recommendation: "ARCHIVE",
      recommendationReason:
        "Nine commits, no README, three years stale, and it conflicts with the actual dotfiles. There is nothing to finish.",
      workRemaining: "tiny",
      workTasks: ["Archive"],
      completionPct: 10,
      complexity: 1,
      maintenanceBurden: 5,
      usefulness: 2,
      commercialPotential: 0,
      ossPotential: 0,
      personalUsefulness: 1,
      portfolioValue: 0,
      ossValue: 0,
      learningValue: 0,
      resurrectionScore: 3,
      epitaph: "Here lies another bashrc.",
      causeOfDeath: "Forgot it existed.",
      bornDate: "2023-10-02",
      overlaps: [],
      facts: ["9 commits, last in Nov 2023", "Private, empty description originally"],
      assumptions: ["Real dotfiles live elsewhere"],
      mvpDefinition: "N/A — archive.",
      milestones: [{ id: "m1", title: "Archive", done: false }],
      taskList: [{ id: "t1", title: "Archive on GitHub", estimate: "tiny" }],
      firstTask: "Archive on GitHub",
      dependencies: [],
      blockers: [],
      definitionOfDone: "Repo archived.",
      analyzedAt,
      source: "seed",
    }),
  },
  {
    id: "demo-homelab-status",
    name: "homelab-status",
    fullName: "demo/homelab-status",
    description: "Uptime and service homepage for a home lab. Actively maintained.",
    isPrivate: true,
    isFork: false,
    language: "TypeScript",
    languages: { TypeScript: 90, CSS: 10 },
    stars: 0,
    forks: 0,
    openIssues: 1,
    openPrs: 0,
    lastCommitAt: "2026-08-16T08:05:00.000Z",
    createdAtGh: "2025-12-01T18:00:00.000Z",
    pushedAt: "2026-08-16T08:05:00.000Z",
    sizeKb: 2100,
    defaultBranch: "main",
    branchCount: 2,
    commitCount: 140,
    readmeQuality: 66,
    hasTests: true,
    hasCi: true,
    hasDeploy: true,
    hasAuth: true,
    hasDb: false,
    todoCount: 2,
    frameworks: ["React", "Docker"],
    topics: ["homelab", "status"],
    htmlUrl: "https://github.com/demo/homelab-status",
    fileTree: ["src/StatusBoard.tsx", "docker-compose.yml", "README.md"],
    packageManifests: ["package.json"],
    userStatus: "active",
    userNotes: "This one is actually in use.",
    queuePosition: null,
    source: "demo",
    analysis: a({
      purpose: "A private status board for home-lab services: up/down, versions, links to Grafana and Uptime Kuma.",
      currentState: "production",
      whatsMissing: ["Documentation"],
      recommendation: "FINISH",
      recommendationReason:
        "This is not a graveyard case — last commit four days ago and it is in production. Keep it off the archive list. Remaining work is a short operator note, not a rewrite.",
      workRemaining: "tiny",
      workTasks: ["Document how to add a service in docker-compose"],
      completionPct: 92,
      complexity: 2,
      maintenanceBurden: 28,
      usefulness: 78,
      commercialPotential: 6,
      ossPotential: 15,
      personalUsefulness: 88,
      portfolioValue: 35,
      ossValue: 14,
      learningValue: 20,
      resurrectionScore: 44,
      epitaph: "Not dead. Stop checking the pulse.",
      causeOfDeath: "None — still running.",
      bornDate: "2025-12-01",
      overlaps: [],
      facts: [
        "Last commit 16 Aug 2026",
        "Deployed via docker-compose",
        "User already marked it active",
      ],
      assumptions: [],
      mvpDefinition: "Already in production.",
      milestones: [{ id: "m1", title: "Operator note", done: false }],
      taskList: [{ id: "t1", title: "Add a service in 8 lines of compose — write that down", estimate: "tiny" }],
      firstTask: "Add a service in 8 lines of compose — write that down",
      dependencies: [],
      blockers: [],
      definitionOfDone: "Future you can add a service without rereading the file.",
      analyzedAt,
      source: "seed",
    }),
  },
];

export function cloneDemoRepos(): Repo[] {
  const repos = structuredClone(DEMO_REPOS) as Repo[];
  const signals = repos.map(toSignals);
  // Enrich each demo repo with the evidence-backed decision fields (readiness,
  // confidence, evidence, remaining work, overlaps) while preserving the
  // hand-authored narrative.
  for (const repo of repos) {
    const computed = analyzeRepo(toSignals(repo), signals);
    repo.analysis = enrichAnalysisWithEvidence(repo.analysis, computed);
  }
  return repos;
}
