/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGraveyardRouteImport } from './routes/_app/graveyard'
import { Route as AppQueueRouteImport } from './routes/_app/queue'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTonightRouteImport } from './routes/_app/tonight'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppGraveyardRoute = AppGraveyardRouteImport.update({
  id: '/graveyard',
  path: '/graveyard',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTonightRoute = AppTonightRouteImport.update({
  id: '/tonight',
  path: '/tonight',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/graveyard': typeof AppGraveyardRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRoute
  '/tonight': typeof AppTonightRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/graveyard': typeof AppGraveyardRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRoute
  '/tonight': typeof AppTonightRoute
  '/': typeof AppIndexRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/graveyard': typeof AppGraveyardRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tonight': typeof AppTonightRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/graveyard'
    | '/queue'
    | '/settings'
    | '/tonight'
    | '/projects/$id'
    | '/api/auth/$'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/graveyard'
    | '/queue'
    | '/settings'
    | '/tonight'
    | '/'
    | '/projects/$id'
    | '/api/auth/$'
    | '/projects'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/graveyard'
    | '/_app/queue'
    | '/_app/settings'
    | '/_app/tonight'
    | '/_app/'
    | '/_app/projects/$id'
    | '/api/auth/$'
    | '/_app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graveyard': {
      id: '/_app/graveyard'
      path: '/graveyard'
      fullPath: '/graveyard'
      preLoaderRoute: typeof AppGraveyardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tonight': {
      id: '/_app/tonight'
      path: '/tonight'
      fullPath: '/tonight'
      preLoaderRoute: typeof AppTonightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppGraveyardRoute: typeof AppGraveyardRoute
  AppQueueRoute: typeof AppQueueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTonightRoute: typeof AppTonightRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGraveyardRoute: AppGraveyardRoute,
  AppQueueRoute: AppQueueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTonightRoute: AppTonightRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
